[project]
name = "blog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "feedgen>=1.0.0",
    "jinja2>=3.1.6",
    "markdown>=3.10.2",
    "pytz>=2025.2",
]
